// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: FlappyBird

#ifndef _FLAPPYBIRD_UI_H
#define _FLAPPYBIRD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * bgmove_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * scroll_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_0_png);    // assets/0.png
LV_IMG_DECLARE(ui_img_1_png);    // assets/1.png
LV_IMG_DECLARE(ui_img_2_png);    // assets/2.png
LV_IMG_DECLARE(ui_img_3_png);    // assets/3.png
LV_IMG_DECLARE(ui_img_4_png);    // assets/4.png
LV_IMG_DECLARE(ui_img_5_png);    // assets/5.png
LV_IMG_DECLARE(ui_img_6_png);    // assets/6.png
LV_IMG_DECLARE(ui_img_7_png);    // assets/7.png
LV_IMG_DECLARE(ui_img_8_png);    // assets/8.png
LV_IMG_DECLARE(ui_img_537399162);    // assets/background-day.png
LV_IMG_DECLARE(ui_img_304849315);    // assets/pipe-green.png
LV_IMG_DECLARE(ui_img_178643817);    // assets/pipe-red.png
LV_IMG_DECLARE(ui_img_base_png);    // assets/base.png
LV_IMG_DECLARE(ui_img_265345687);    // assets/redbird-downflap.png
LV_IMG_DECLARE(ui_img_message_png);    // assets/message.png
LV_IMG_DECLARE(ui_img_1833143324);    // assets/bluebird-downflap.png
LV_IMG_DECLARE(ui_img_76878604);    // assets/yellowbird-downflap.png
LV_IMG_DECLARE(ui_img_185721447);    // assets/yellowbird-upflap.png
LV_IMG_DECLARE(ui_img_548131138);    // assets/bluebird-midflap.png
LV_IMG_DECLARE(ui_img_cloud_png);    // assets/cloud.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
