// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: FlappyBird

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Score;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Bg1;
extern lv_obj_t * ui_ImgBg1;
extern lv_obj_t * ui_ImgBg2;
extern lv_obj_t * ui_ImgBg3;
extern lv_obj_t * ui_ImgBg4;
extern lv_obj_t * ui_wall1;
extern lv_obj_t * ui_wall2;
extern lv_obj_t * ui_wall4;
extern lv_obj_t * ui_wall5;
extern lv_obj_t * ui_wall6;
extern lv_obj_t * ui_wall7;
extern lv_obj_t * ui_wall8;
extern lv_obj_t * ui_wall10;
extern lv_obj_t * ui_wall9;
extern lv_obj_t * ui_wall3;
extern lv_obj_t * ui_wall11;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_road1;
extern lv_obj_t * ui_road2;
extern lv_obj_t * ui_road3;
extern lv_obj_t * ui_road4;
extern lv_obj_t * ui_Panel2;
extern void ui_event_Trigger(lv_event_t * e);
extern lv_obj_t * ui_Trigger;
extern lv_obj_t * ui_Bird1;
extern void ui_event_Start(lv_event_t * e);
extern lv_obj_t * ui_Start;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Image25;
extern lv_obj_t * ui_Image26;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

