// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: FlappyBird

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Score = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Image18 = NULL;
lv_obj_t * ui_Image19 = NULL;
lv_obj_t * ui_Image20 = NULL;
lv_obj_t * ui_Image21 = NULL;
lv_obj_t * ui_Image22 = NULL;
lv_obj_t * ui_Image23 = NULL;
lv_obj_t * ui_Bg1 = NULL;
lv_obj_t * ui_ImgBg1 = NULL;
lv_obj_t * ui_ImgBg2 = NULL;
lv_obj_t * ui_ImgBg3 = NULL;
lv_obj_t * ui_ImgBg4 = NULL;
lv_obj_t * ui_wall1 = NULL;
lv_obj_t * ui_wall2 = NULL;
lv_obj_t * ui_wall4 = NULL;
lv_obj_t * ui_wall5 = NULL;
lv_obj_t * ui_wall6 = NULL;
lv_obj_t * ui_wall7 = NULL;
lv_obj_t * ui_wall8 = NULL;
lv_obj_t * ui_wall10 = NULL;
lv_obj_t * ui_wall9 = NULL;
lv_obj_t * ui_wall3 = NULL;
lv_obj_t * ui_wall11 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_road1 = NULL;
lv_obj_t * ui_road2 = NULL;
lv_obj_t * ui_road3 = NULL;
lv_obj_t * ui_road4 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Trigger = NULL;
lv_obj_t * ui_Bird1 = NULL;
lv_obj_t * ui_Start = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Image24 = NULL;
lv_obj_t * ui_Image25 = NULL;
lv_obj_t * ui_Image26 = NULL;
// event funtions
void ui_event_Trigger(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSING) {
        lv_indev_t * indev = lv_indev_get_act();
        if(indev == NULL)  return;

        lv_point_t vect;
        lv_indev_get_vect(indev, &vect);

        lv_coord_t x = (lv_obj_get_x(target) - 340) + vect.x; // 360 - 40/2  
        lv_coord_t y = (lv_obj_get_y(target) - 301) + vect.y; // 360 - 118/2 
        printf("x = %d, y = %d\n", x, y);
        _ui_basic_set_property(ui_Trigger, _UI_BASIC_PROPERTY_POSITION_X,  x);
        _ui_basic_set_property(ui_Trigger, _UI_BASIC_PROPERTY_POSITION_Y,  y);
    }
}

void ui_event_Start(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        bgmove_Animation(ui_Bg1, 0);
        scroll_Animation(ui_Score, 1000);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 720);
    lv_obj_set_height(ui_Panel1, 130);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -335);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x4EC0CA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Score = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Score, 100);
    lv_obj_set_height(ui_Score, 800);
    lv_obj_set_x(ui_Score, 0);
    lv_obj_set_y(ui_Score, -300);
    lv_obj_set_align(ui_Score, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Score, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Score, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Score, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Score, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_image_create(ui_Score);
    lv_image_set_src(ui_Image3, &ui_img_0_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image3, -12);
    lv_obj_set_y(ui_Image3, 0);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_image_create(ui_Score);
    lv_image_set_src(ui_Image4, &ui_img_1_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image4, 18);
    lv_obj_set_y(ui_Image4, 0);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_image_create(ui_Score);
    lv_image_set_src(ui_Image10, &ui_img_0_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image10, -12);
    lv_obj_set_y(ui_Image10, 50);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_image_create(ui_Score);
    lv_image_set_src(ui_Image11, &ui_img_2_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image11, 18);
    lv_obj_set_y(ui_Image11, 50);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_image_create(ui_Score);
    lv_image_set_src(ui_Image12, &ui_img_0_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image12, -12);
    lv_obj_set_y(ui_Image12, 100);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_image_create(ui_Score);
    lv_image_set_src(ui_Image13, &ui_img_3_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image13, 18);
    lv_obj_set_y(ui_Image13, 100);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_image_create(ui_Score);
    lv_image_set_src(ui_Image14, &ui_img_0_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image14, -12);
    lv_obj_set_y(ui_Image14, 150);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image15 = lv_image_create(ui_Score);
    lv_image_set_src(ui_Image15, &ui_img_4_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image15, 18);
    lv_obj_set_y(ui_Image15, 150);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image16 = lv_image_create(ui_Score);
    lv_image_set_src(ui_Image16, &ui_img_0_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image16, -12);
    lv_obj_set_y(ui_Image16, 200);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image17 = lv_image_create(ui_Score);
    lv_image_set_src(ui_Image17, &ui_img_5_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image17, 18);
    lv_obj_set_y(ui_Image17, 200);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image18 = lv_image_create(ui_Score);
    lv_image_set_src(ui_Image18, &ui_img_0_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image18, -12);
    lv_obj_set_y(ui_Image18, 250);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image19 = lv_image_create(ui_Score);
    lv_image_set_src(ui_Image19, &ui_img_6_png);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image19, 18);
    lv_obj_set_y(ui_Image19, 250);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image20 = lv_image_create(ui_Score);
    lv_image_set_src(ui_Image20, &ui_img_0_png);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image20, -12);
    lv_obj_set_y(ui_Image20, 300);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image21 = lv_image_create(ui_Score);
    lv_image_set_src(ui_Image21, &ui_img_7_png);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image21, 18);
    lv_obj_set_y(ui_Image21, 300);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image22 = lv_image_create(ui_Score);
    lv_image_set_src(ui_Image22, &ui_img_0_png);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image22, -12);
    lv_obj_set_y(ui_Image22, 350);
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image23 = lv_image_create(ui_Score);
    lv_image_set_src(ui_Image23, &ui_img_8_png);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image23, 18);
    lv_obj_set_y(ui_Image23, 350);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Bg1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Bg1);
    lv_obj_set_width(ui_Bg1, 1152);
    lv_obj_set_height(ui_Bg1, lv_pct(100));
    lv_obj_set_x(ui_Bg1, 216);
    lv_obj_set_y(ui_Bg1, 0);
    lv_obj_set_align(ui_Bg1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Bg1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgBg1 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_ImgBg1, &ui_img_537399162);
    lv_obj_set_width(ui_ImgBg1, LV_SIZE_CONTENT);   /// 288
    lv_obj_set_height(ui_ImgBg1, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_ImgBg1, -288);
    lv_obj_set_y(ui_ImgBg1, -14);
    lv_obj_set_align(ui_ImgBg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgBg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_ImgBg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgBg2 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_ImgBg2, &ui_img_537399162);
    lv_obj_set_width(ui_ImgBg2, LV_SIZE_CONTENT);   /// 288
    lv_obj_set_height(ui_ImgBg2, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_ImgBg2, 0);
    lv_obj_set_y(ui_ImgBg2, -14);
    lv_obj_set_align(ui_ImgBg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgBg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_ImgBg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgBg3 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_ImgBg3, &ui_img_537399162);
    lv_obj_set_width(ui_ImgBg3, LV_SIZE_CONTENT);   /// 288
    lv_obj_set_height(ui_ImgBg3, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_ImgBg3, 288);
    lv_obj_set_y(ui_ImgBg3, -14);
    lv_obj_set_align(ui_ImgBg3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgBg3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_ImgBg3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgBg4 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_ImgBg4, &ui_img_537399162);
    lv_obj_set_width(ui_ImgBg4, LV_SIZE_CONTENT);   /// 288
    lv_obj_set_height(ui_ImgBg4, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_ImgBg4, -576);
    lv_obj_set_y(ui_ImgBg4, -14);
    lv_obj_set_align(ui_ImgBg4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgBg4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_ImgBg4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wall1 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_wall1, &ui_img_304849315);
    lv_obj_set_width(ui_wall1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wall1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wall1, -286);
    lv_obj_set_y(ui_wall1, 188);
    lv_obj_set_align(ui_wall1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wall1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_wall1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wall2 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_wall2, &ui_img_304849315);
    lv_obj_set_width(ui_wall2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wall2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wall2, -286);
    lv_obj_set_y(ui_wall2, -234);
    lv_obj_set_align(ui_wall2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wall2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_wall2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_wall2, 1800);

    ui_wall4 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_wall4, &ui_img_304849315);
    lv_obj_set_width(ui_wall4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wall4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wall4, -139);
    lv_obj_set_y(ui_wall4, -315);
    lv_obj_set_align(ui_wall4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wall4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_wall4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_wall4, 1800);

    ui_wall5 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_wall5, &ui_img_304849315);
    lv_obj_set_width(ui_wall5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wall5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wall5, 3);
    lv_obj_set_y(ui_wall5, 207);
    lv_obj_set_align(ui_wall5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wall5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_wall5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wall6 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_wall6, &ui_img_304849315);
    lv_obj_set_width(ui_wall6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wall6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wall6, 3);
    lv_obj_set_y(ui_wall6, -203);
    lv_obj_set_align(ui_wall6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wall6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_wall6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_wall6, 1800);

    ui_wall7 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_wall7, &ui_img_304849315);
    lv_obj_set_width(ui_wall7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wall7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wall7, 148);
    lv_obj_set_y(ui_wall7, 58);
    lv_obj_set_align(ui_wall7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wall7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_wall7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wall8 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_wall8, &ui_img_304849315);
    lv_obj_set_width(ui_wall8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wall8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wall8, 148);
    lv_obj_set_y(ui_wall8, -360);
    lv_obj_set_align(ui_wall8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wall8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_wall8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_wall8, 1800);

    ui_wall10 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_wall10, &ui_img_304849315);
    lv_obj_set_width(ui_wall10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wall10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wall10, -435);
    lv_obj_set_y(ui_wall10, -320);
    lv_obj_set_align(ui_wall10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wall10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_wall10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_wall10, 1800);

    ui_wall9 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_wall9, &ui_img_304849315);
    lv_obj_set_width(ui_wall9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wall9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wall9, -433);
    lv_obj_set_y(ui_wall9, 129);
    lv_obj_set_align(ui_wall9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wall9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_wall9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wall3 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_wall3, &ui_img_304849315);
    lv_obj_set_width(ui_wall3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wall3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wall3, 314);
    lv_obj_set_y(ui_wall3, -219);
    lv_obj_set_align(ui_wall3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wall3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_wall3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_wall3, 1800);

    ui_wall11 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_wall11, &ui_img_304849315);
    lv_obj_set_width(ui_wall11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wall11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wall11, 313);
    lv_obj_set_y(ui_wall11, 202);
    lv_obj_set_align(ui_wall11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wall11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_wall11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_Image2, &ui_img_178643817);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -140);
    lv_obj_set_y(ui_Image2, 126);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_road1 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_road1, &ui_img_base_png);
    lv_obj_set_width(ui_road1, LV_SIZE_CONTENT);   /// 336
    lv_obj_set_height(ui_road1, LV_SIZE_CONTENT);    /// 112
    lv_obj_set_x(ui_road1, -265);
    lv_obj_set_y(ui_road1, 185);
    lv_obj_set_align(ui_road1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_road1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_road1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_road2 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_road2, &ui_img_base_png);
    lv_obj_set_width(ui_road2, LV_SIZE_CONTENT);   /// 336
    lv_obj_set_height(ui_road2, LV_SIZE_CONTENT);    /// 112
    lv_obj_set_x(ui_road2, 71);
    lv_obj_set_y(ui_road2, 185);
    lv_obj_set_align(ui_road2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_road2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_road2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_road3 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_road3, &ui_img_base_png);
    lv_obj_set_width(ui_road3, LV_SIZE_CONTENT);   /// 336
    lv_obj_set_height(ui_road3, LV_SIZE_CONTENT);    /// 112
    lv_obj_set_x(ui_road3, -599);
    lv_obj_set_y(ui_road3, 185);
    lv_obj_set_align(ui_road3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_road3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_road3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_road4 = lv_image_create(ui_Bg1);
    lv_image_set_src(ui_road4, &ui_img_base_png);
    lv_obj_set_width(ui_road4, LV_SIZE_CONTENT);   /// 336
    lv_obj_set_height(ui_road4, LV_SIZE_CONTENT);    /// 112
    lv_obj_set_x(ui_road4, 287);
    lv_obj_set_y(ui_road4, 185);
    lv_obj_set_align(ui_road4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_road4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_road4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 720);
    lv_obj_set_height(ui_Panel2, 130);
    lv_obj_set_x(ui_Panel2, 1);
    lv_obj_set_y(ui_Panel2, 305);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xDED895), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Trigger = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Trigger, 40);
    lv_obj_set_height(ui_Trigger, 118);
    lv_obj_set_x(ui_Trigger, -289);
    lv_obj_set_y(ui_Trigger, -86);
    lv_obj_set_align(ui_Trigger, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Trigger, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Trigger, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Trigger, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Trigger, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bird1 = lv_image_create(ui_Trigger);
    lv_image_set_src(ui_Bird1, &ui_img_265345687);
    lv_obj_set_width(ui_Bird1, LV_SIZE_CONTENT);   /// 34
    lv_obj_set_height(ui_Bird1, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Bird1, 5);
    lv_obj_set_y(ui_Bird1, -36);
    lv_obj_set_align(ui_Bird1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bird1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Bird1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Start = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Start, 200);
    lv_obj_set_height(ui_Start, 50);
    lv_obj_set_x(ui_Start, 0);
    lv_obj_set_y(ui_Start, 233);
    lv_obj_set_align(ui_Start, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Start, lv_color_hex(0x528120), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Start);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "START");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image1, &ui_img_message_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 184
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 267
    lv_obj_set_x(ui_Image1, -6);
    lv_obj_set_y(ui_Image1, 432);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image5, &ui_img_1833143324);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 34
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image5, -308);
    lv_obj_set_y(ui_Image5, 188);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image6, &ui_img_265345687);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 34
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image6, -275);
    lv_obj_set_y(ui_Image6, 280);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image7, &ui_img_76878604);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 34
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image7, -177);
    lv_obj_set_y(ui_Image7, 262);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image8, &ui_img_185721447);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 34
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image8, 217);
    lv_obj_set_y(ui_Image8, 211);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image9, &ui_img_548131138);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 34
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image9, 281);
    lv_obj_set_y(ui_Image9, 284);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image24 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image24, &ui_img_cloud_png);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 288
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 68
    lv_obj_set_x(ui_Image24, -218);
    lv_obj_set_y(ui_Image24, -346);
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image25 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image25, &ui_img_cloud_png);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 288
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 68
    lv_obj_set_x(ui_Image25, -6);
    lv_obj_set_y(ui_Image25, -358);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image26 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image26, &ui_img_cloud_png);
    lv_obj_set_width(ui_Image26, LV_SIZE_CONTENT);   /// 288
    lv_obj_set_height(ui_Image26, LV_SIZE_CONTENT);    /// 68
    lv_obj_set_x(ui_Image26, 274);
    lv_obj_set_y(ui_Image26, -351);
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Trigger, ui_event_Trigger, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Start, ui_event_Start, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Panel1 = NULL;
    ui_Score = NULL;
    ui_Image3 = NULL;
    ui_Image4 = NULL;
    ui_Image10 = NULL;
    ui_Image11 = NULL;
    ui_Image12 = NULL;
    ui_Image13 = NULL;
    ui_Image14 = NULL;
    ui_Image15 = NULL;
    ui_Image16 = NULL;
    ui_Image17 = NULL;
    ui_Image18 = NULL;
    ui_Image19 = NULL;
    ui_Image20 = NULL;
    ui_Image21 = NULL;
    ui_Image22 = NULL;
    ui_Image23 = NULL;
    ui_Bg1 = NULL;
    ui_ImgBg1 = NULL;
    ui_ImgBg2 = NULL;
    ui_ImgBg3 = NULL;
    ui_ImgBg4 = NULL;
    ui_wall1 = NULL;
    ui_wall2 = NULL;
    ui_wall4 = NULL;
    ui_wall5 = NULL;
    ui_wall6 = NULL;
    ui_wall7 = NULL;
    ui_wall8 = NULL;
    ui_wall10 = NULL;
    ui_wall9 = NULL;
    ui_wall3 = NULL;
    ui_wall11 = NULL;
    ui_Image2 = NULL;
    ui_road1 = NULL;
    ui_road2 = NULL;
    ui_road3 = NULL;
    ui_road4 = NULL;
    ui_Panel2 = NULL;
    ui_Trigger = NULL;
    ui_Bird1 = NULL;
    ui_Start = NULL;
    ui_Label2 = NULL;
    ui_Image1 = NULL;
    ui_Image5 = NULL;
    ui_Image6 = NULL;
    ui_Image7 = NULL;
    ui_Image8 = NULL;
    ui_Image9 = NULL;
    ui_Image24 = NULL;
    ui_Image25 = NULL;
    ui_Image26 = NULL;

}
